DROP TABLE IF EXISTS vehicles.Bicycle;
DROP TABLE IF EXISTS vehicles.Motorcycle;
DROP TABLE IF EXISTS vehicles.Car;
DROP TABLE IF EXISTS vehicles.Vehicle;
DROP SCHEMA IF EXISTS vehicles;

DROP TABLE IF EXISTS racing.Results;
DROP TABLE IF EXISTS racing.Races;
DROP TABLE IF EXISTS racing.Cars;
DROP TABLE IF EXISTS racing.Classes;
DROP SCHEMA IF EXISTS racing;

DROP TABLE IF EXISTS hb.Booking;
DROP TABLE IF EXISTS hb.Customer;
DROP TABLE IF EXISTS hb.Room;
DROP TABLE IF EXISTS hb.Hotel;
DROP SCHEMA IF EXISTS hb;

DROP TABLE IF EXISTS org.Tasks;
DROP TABLE IF EXISTS org.Projects;
DROP TABLE IF EXISTS org.Employees;
DROP TABLE IF EXISTS org.Roles;
DROP TABLE IF EXISTS org.Departments;
DROP SCHEMA IF EXISTS org;
